# Generated by Django 5.2.4 on 2025-08-05 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamlens_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='꿈 유형')),
            ],
            options={
                'verbose_name': '꿈 유형',
                'verbose_name_plural': '꿈 유형 목록',
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='감정')),
            ],
            options={
                'verbose_name': '감정',
                'verbose_name_plural': '감정 목록',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='꿈꾼 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('interpretation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='dreamlens_core.interpretation', verbose_name='해몽')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('dream_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='dreamlens_core.dreamtype', verbose_name='꿈 유형')),
                ('emotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='dreamlens_core.emotion', verbose_name='감정')),
            ],
            options={
                'verbose_name': '꿈 일기',
                'verbose_name_plural': '꿈 일기 목록',
                'ordering': ['-date'],
            },
        ),
    ]
